kind = "web"
previewPath = "/"
title = "Ozy Snaker"
version = "1.0.0"
id = "artifacts/ozy-snaker"
router = "path"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 25480

[services.development]
run = "pnpm --filter @workspace/ozy-snaker run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ozy-snaker", "run", "build" ]
serve = "static"
publicDir = "artifacts/ozy-snaker/dist/public"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "25480"
BASE_PATH = "/"
